### ISSUE TITLE
Update for v1.4

### ISSUE THREAD

**Issue by langner** [cclib/cclib.github.io#16]
This is for coordinating any work that'll need to be done for cclib v1.4, which I'd like to release in two weeks (Aptil 24th).

**Comment by szl0072** [comment]
I still got error when I was tying to run testall.py:
` 
Traceback (most recent call last):
  File "testall.py", line 14, in <module>
    from . import test_data
ImportError: cannot import name 'test_data'`

**Comment by langner** [comment]
What version are you using and how was it installed?

**Comment by szl0072** [comment]
I downloaded the current development version and followed the `how to install` page to install.  I use `python setup build`, then `python setup install`. Maybe I missed something when I did the above steps? I looked through the main repo and it said migrate to this new issue for further discussion. However, I could not trace back to that page now.

**Comment by langner** [comment]
But why did you download v1.4?

**Comment by szl0072** [comment]
I got the `version="1.5.2"`, read from setup.py. Apart from the above error, the `run_regressions.py` description in the documentation page  should be changed, since there is no such a file in the test folder now. I did not have a lot of experience to build whole code bases in the past, so that might be a good excuse for me to have tons of issues. Thus, I may miss some of the key steps to get the software going. I am sorry for any of that lacking of experience.
